### ISSUE TITLE
so-xp.obo was removed

### ISSUE THREAD

**Issue by susannasiebert** [The-Sequence-Ontology/SO-Ontologies#473] opened 2019-07-26 14:23 UTC
Commit 756b617e9cdf0dadffc7ae30251f69742a58b095 removed the `releases/so-xp.owl/so-xp.obo` file which is what we use in CIViC to scrape sequence ontology terms. Is there a reason why this file was removed? Is there an alternate file we can use?

Also cc'ing @obigriffith @malachig @kkrysiak

**Comment by davidwsant** [comment] 2019-07-31 23:11
Hi Susana,

I have looked at the old file and it appears as though the so-xp.obo is the exact same format as the so.obo file. According to the Git logs, the last time the so-xp.obo was actually changed was in October of 2016, indicating that it has not been updating along with the other files. I am going to check with some other people that have worked with SO and see if they know any more about the so-xp.obo file, but for the meantime please try the so.obo file. Please respond to this post if it works, because I do not want to close the issue until it has been confirmed that it works. 

Thank you,

Dave

**Comment by davidwsant** [comment] 2019-10-15 17:42
Hi Susana, 

I have discussed the so-xp.obo with some of the other members of the group. Although the file has not been updated, we are concerned that the new ones do not have the cross products. As such, I have put the files back into the newer commits so that you can continue to use them. I am investigating some tools to see if they will update the cross-product terms. I apologize for the delay. 

Thanks,

Dave

**Closed by davidwsant** 2019-10-15 17:42 UTC
